//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DONHANG
    {
        public int ID { get; set; }
        public int STT { get; set; }
        public string MABANH { get; set; }
        public string MA_DONHANG { get; set; }
        public Nullable<int> SL_MUA { get; set; }
    
        public virtual BANH BANH { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
